service: serverless-invoice-generator

functions: ${file(./resources/functions.yml)}
resources: ${file(./resources/resources.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${self:custom.params.stage}
  runtime: nodejs12.x
  profile: ${self:custom.params.profile}
  environment:
    REGION: ${self:custom.params.region}
    STAGE: ${self:custom.params.stage}
    BUCKET: ${self:custom.params.bucket}
    PROFILE: ${self:custom.params.profile}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:ListObject'
        - 's3:GetObject'
      Resource: arn:aws:s3:::${self:provider.environment.BUCKET}/*

custom:
  params:
    stage: ${opt:stage, 'local'}
    profile: ${opt:profile, 'hajime'}
    region: ${opt:region, 'eu-central-1'}
    bucket: ${opt:pdf-bucket, 'generated-invoices-${self:custom.params.stage}'}

  serverless-offline:
    port: 4000

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - puppeteer

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
