service: serverless-invoice-generator

functions: ${file(./resources/functions.yml)}
resources: ${file(./resources/resources.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${opt:stage, 'local'}
  runtime: nodejs12.x
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:ListObject'
        - 's3:GetObject'
      Resource: 'arn:aws:s3::::hajime-files'

custom:
  serverless-offline:
    port: 4000

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - puppeteer

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
